### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by everythingability** [bepitulaz/google-sheets-midi-sequencer#1]
Share your spreadsheet URL, (view only obv) ... replace the /edit with /copy then people don't have go monkeying around re-making this.

Great work btw.

**Comment by bepitulaz** [comment]
Good idea. I will put it on Readme file.

**Comment by bepitulaz** [comment]
@everythingability done. It's now in the [readme](https://github.com/bepitulaz/google-sheets-midi-sequencer/blob/main/README.md#the-sheet). Thanks for the suggestion.
